package com.example.sistemanutricao.model.enuns;

public enum Tag {
    PROTEINA_BAIXA,
    PROTEINA_MEDIA,
    PROTEINA_ALTA,
    CARBOIDRATO_BAIXO,
    CARBOIDRATO_MEDIO,
    CARBOIDRATO_ALTO,
    GORDURA_BAIXA,
    GORDURA_MEDIA,
    GORDURA_ALTA,
    SODIO_BAIXO,
    SODIO_MEDIO,
    SODIO_ALTO,
    GORDURA_SATURADA_BAIXA,
    GORDURA_SATURADA_MEDIA,
    GORDURA_SATURADA_ALTA;
}
